#! /usr/bin/env python2
"""
usage: distress <command> [<args>...]

The most commonly used commands are:
    add     add file to  network
    del     remove file from network
    get     retrieve file
    list    list all local reciepts
    info    view information about file
    import  import reciept file locally
    export  export reciept for others

See 'distress <command> --help' for more information on a specific command.
"""

import sys
from subprocess import call
from ext.docopt import docopt

__version__='v0.1.0'

## Force usage of python 2.* 
PYTHON_EXEC='python2'

if __name__ == '__main__':

    args = docopt (__doc__,
                   version=__version__,
                   options_first=True)

    argv = [args['<command>']] + args['<args>']
    dmod =  args['<command>']  + '.py'

    try:
        with open (dmod, "r") as _: pass # does command exist?

        exit (call ([PYTHON_EXEC, dmod] + argv))
    except IOError as err:
        exit("%r is not a valid command. See 'distress help'." % 
                                            (args['<command>'], sys.argv[0]))

