#! /usr/bin/env python
"""
usage: distress <command> [<args>...]

The most commonly used commands are:
    add     add file to  network
    del     remove file from network
    get     retrieve file
    list    list all local reciepts
    info    view information about file
    import  import reciept file locally
    export  export reciept for others

See 'distress <command> --help' for more information on a specific command.
"""



"""
usage: git [--version] [--exec-path=<path>] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=<path>] [--work-tree=<path>]
           [-c <name>=<value>] [--help]
           <command> [<args>...]

options:
   -c <name=value>
   -h, --help
   -p, --paginate

The most commonly used git commands are:
   add        Add file contents to the index
   branch     List, create, or delete branches
   checkout   Checkout a branch or paths to the working tree
   clone      Clone a repository into a new directory
   commit     Record changes to the repository
   push       Update remote refs along with associated objects
   remote     Manage set of tracked repositories

See 'git help <command>' for more information on a specific command.

"""
from subprocess import call
from docopt     import docopt


if __name__ == '__main__':

    args = docopt (__doc__,
                   version='distress 0.1',
                   options_first=True)

    argv = [args['<command>']] + args['<args>']
    dmod =  args['<command>']  + '.py'

    try:
        fi = open (dmod, "r")
         # does command exist?

        exit (call (['python', dmod] + argv))
    except IOError as err:
        exit("%r is not a valid command. See 'distress help'." % args['<command>'])
        







