#! /usr/bin/env python2
"""
usage: distress <command> [<args>...]

The most commonly used commands are:
    add     add file to  network
    del     remove file from network
    get     retrieve file
    list    list all local reciepts
    info    view information about file
    import  import reciept file locally
    export  export reciept for others

See 'distress <command> --help' for more information on a specific command.
"""

import sys
from os import sep as OSSEP
from subprocess import call
from ui._config import getargs

## Force usage of python 2.*
PYTHON_EXEC='python2'

## Command extention and directory
CMD_EXT='.py'
CMD_DIR='ui' + OSSEP

if __name__ == '__main__':

    args = getargs(__doc__, options_first=True)

    argv = [args['<command>']] + args['<args>']
    dmod = CMD_DIR + args['<command>'] + CMD_EXT

    try:
        if args['<command>'].startswith('_'): raise IOError
        with open (dmod, "r") as _: pass # does command exist?

        exit (call ([PYTHON_EXEC, dmod] + argv))
    except IOError as err:
        exit("%r is not a valid command. See '%s help'." %
                                            (args['<command>'], sys.argv[0]))

